version: '3.8'

services:
  postgres:
    container_name: "qarwett-postgres"
    image: "postgres:latest"
    restart: unless-stopped
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD
    ports:
      - "5432:5432"

  qarwett:
    container_name: "qarwett-telegram"
    image: "qarwett:latest"
    restart: unless-stopped
    volumes:
      - ./.calendars:/app/.calendars
    environment:
      - CONFIG_PATH=./config/dev.yaml
    ports:
      - "80:8888"