version: '3.8'

services:
  postgres:
    container_name: "qarwett-postgres"
    image: "postgres:latest"
    restart: unless-stopped
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD
    ports:
      - "5432:5432"